### PR TITLE
Formatted citations

### PR DESCRIPTION
**Pull request by lambtho12**
This PR allows the user to paste a fully-formatted citation by pressing <c-c> in the picker. This solves (partially) https://github.com/nvim-telescope/telescope-bibtex.nvim/pull/33

It is still a WIP as it currently only supports author, titles and year. Users can customize the format by using the option `citation_format`.

TODO:
- [x] Support for all usual fields (key, publisher, etc)
- [x] Allow trimming author first names (_e.g._ Newton, Issac -> Newton, I.) **new user option**
- [x] Allow limiting max number of authors (replace remaining authors by _et al._) **new user option**
- [x] Add citekey (parsing and for user template)
- [x] Add entry_type filed (parsing and for user template)
- [x] Simplify `parse_entry` so it creates the dict as a loop with all fields available
- [x] Put helpers in separate file
- [x] Format escaped accents

---
The first commit only makes minor style changes, in order to be coherent across all code. I took the liberty to add a `.stylua` file at the root of the repo so developers can all share the same style. Feel free to modify it to better fit your liking.

### CODE REVIEW

**Comment by lambtho12** [comment]
@noahares could you check all this before I continue?

**Comment by noahares** [comment]
I will have a look later today. I like the idea of a uniform lua style.

**Comment by noahares** [comment]
I am happy with the style file. I think these are good defaults. 
I tried running your additions, but get `E5108: Error executing lua ...pt/telescope-bibtex/lua/telescope/_extensions/bibtex.lua:301: attempt to concatenate a nil value`
If this is not intentional, I will try to figure out whats wrong with it tomorrow.
Otherwise I have nothing to complain about with your additions. 
It might be time to spread the code over multiple files, however. 
Maybe you can move your helper functions to a new file? 
I would do the same with the other actions in the near future.

**Comment by lambtho12** [comment]
> I am happy with the style file. I think these are good defaults.

Perfect. I tend to prefer double quotes instead of singles and 80 char lines instead of 120, but I adapted to be closer to the code you had before.

>  I tried running your additions, but get E5108: Error executing lua ...pt/telescope-bibtex/lua/telescope/_extensions/bibtex.lua:301: attempt to concatenate a nil value

That is strange. I tested it on lots of different stuff and did encounter an issue...

Could you post a minimal .bib file with a few references that give that error so I can debug? Seems like the error is in the `trim_firstname` function. I guess you only have the author name and not firstname. I should add a check before trying to trim the firstname :smile: 

>  Otherwise I have nothing to complain about with your additions.

Nice!

>  It might be time to spread the code over multiple files, however.
Maybe you can move your helper functions to a new file?
I would do the same with the other actions in the near future.

Sure thing. I can create a `helpers.lua` or something.

**Comment by noahares** [comment]
> Perfect. I tend to prefer double quotes instead of singles and 80 char lines instead of 120, but I adapted to be closer to the code you had before.

80 char lines are good. I actually use 80 for other code I write. Didn't know about luastyle until you mentioned it so I didn't bother setting it.

The fix seems to work. I now get the expected output without errors. There is however another bug with escaped Umlaute and other such characters. If I pick the following entry, the last name is cut of after the `{`

```
@article{dolan2002benchmarking,
  title={Benchmarking optimization software with performance profiles},
  author={Dolan, Elizabeth D and Mor{\'e}, Jorge J},
  journal={Mathematical programming},
  volume={91},
  number={2},
  pages={201--213},
  year={2002},
  publisher={Springer}
}
```

**Comment by lambtho12** [comment]
Thanks for pointing it out. I will fix that tomorrow!

**Comment by lambtho12** [comment]
Should be ok now. However, I did not handled escaped characters in any special way. _I.e._, the example provided would give `Dolan, E. and Mor{\'e}, J. (2002), Benchmarking optimization software with performance profiles.`

I do not think that the plugin should replace such characters by itself as it will depend on the type used in neovim. IMO this is ok like that.

---
As a side note, I am not sure how author names should be trimmed when there is a middle name (or middle initial). For instance in you example, there is `Dolan, Elizabeth D`. Currently it becomes `Dolan E.`. Should it become `Dolan, E. D.`?
Now that I think of it, should we even keep the comma? Or should it become `Dolan E.` or  `Dolan E. D.`.?

What do you think? I am not sure, but I would be in favor of keeping all initials, so we should have `Dolan, E. D.` or `Dolan E. D.`

**Comment by noahares** [comment]
Yes, the characters should not be replaced. I thought of this once when displaying the preview, but quickly decided to not do this.

I do not have an opinion about the trimming. From what I found online about APA it says that middle names are abbreviated with a comma after the last name.
So it would be `Dolan, E. D.` in this case. I agree on keeping all initials.

**Comment by erooke** [comment]
> Should be ok now. However, I did not handled escaped characters in any special way. _I.e._, the example provided would give `Dolan, E. and Mor{\'e}, J. (2002), Benchmarking optimization software with performance profiles.`
> 
> I do not think that the plugin should replace such characters by itself as it will depend on the type used in neovim. IMO this is ok like that.

To my knowledge the `{}` can be safely discarded, afaik the only meaning that the `{}` confer is to preserve the capitalization as bibtex applies its own capitalization to titles.

What filetype would change it so `\'e` shouldn't expand to `é`?

**Comment by lambtho12** [comment]
> To my knowledge the {} can be safely discarded, afaik the only meaning that the {} confer is to preserve the capitalization as bibtex applies its own capitalization to titles.

Ok, I have always been wondering why Zotero put all thoses `{}`. It makes sense. I will strip the `{}` from all fields then to clean them up.

> What filetype would change it so \'e shouldn't expand to é?

I did not meant _filetype_, but _encoding_. 
In anycase, I am not a first-hand developer and have never fooled around with different encoding so I am not sure exactly how this might screw things up. This comment was more a precaution. I'd rather keep it `\'e` than have it break for people having other setups. 
I guess I could add a check for the file encoding. If encoding supports accent, I could have them all replaced automatically...

**Comment by lambtho12** [comment]
> So it would be `Dolan, E. D.` in this case. I agree on keeping all initials.

Ok. I will make it keep every initial then.

**Comment by erooke** [comment]
Ah yeah, I wasn't even thinking about file encodings. I'm all for leaving them as is (especially as everyone else seems cool with it) I was just curious under what circumstances the expansion wouldn't apply.

-------- Original Message --------

**Comment by lambtho12** [comment]
> Ah yeah, I wasn't even thinking about file encodings. I'm all for leaving them as is (especially as everyone else seems cool with it) I was just curious under what circumstances the expansion wouldn't apply.

Too late, I am already building a gigantic table based on the bibtex translator for zotero...

**Comment by lambtho12** [comment]
@noahares, I think it is all good now. I also took the liberty to improve the documentation and (hopfully) make it easier to understand.

The history is a bit messy (I tend to over-commit a lot 😄). Do not hesitate to squash these when you merge!

**Comment by noahares** [comment]
Alright, I will have a look at it :) Thanks again for implementing this feature!

**Comment by noahares** [comment]
Looks good to me. I fixed some stuff in the readme. There is one issue I found by accident: I have one entry where the author names are split across multiple lines. When I try to paste the formatted citations I get an error. 
This is because I split entries by `\n` which is probably not right to do. So the issue should disappear when I find a fix for this. Since this breaks your feature (and only results in a mild annoyance when using the existing pickers) I will push the fix to this branch before I merge it. Sorry for that!

**Comment by lambtho12** [comment]
> Looks good to me. I fixed some stuff in the readme. 

Thanks for that! I should have proof-read one more time :sweat_smile: 

> This is because I split entries by `\n` which is probably not right to do.

I have never seen that before. Is it common? Is it even [valid bibtex](https://www.bibtex.com/f/author-field/)?  How do you generate you bibliography (Mendeley, Zotero, etc?) Have you ever tried using these in LaTex? 
If it is not valid bibtex, I think you should instead focus on fixing you bibliography instead of adding fixes for non-existent features, no? If you are not using a reference manager, I suggest you try Zotero (it's free and open source). You could import you existing bibtex file and export it back, maybe it will all be reformatted properly. (Besides that, Zotero is a wonderful tool to help you organize your stuff, but that is an other topic :smile: )

**Comment by noahares** [comment]
I used this bib file for my bachelor thesis so I am pretty sure it works. 
I use standard pdflatex with `\bibliography` and copy references from scholar via their bibtex option, no reference manager.
I just checked the original entry on scholar and there it does not have a linebreak, so I guess that happend at some point when I formatted the file or tried to brake stuff in tests.
In this case I think this issue can be ignored. However I do not like that this throws a error. I will add a warning to the `read_file` function that takes care of this.

**Comment by noahares** [comment]
One last thing. Does bibtex require an author field. I have another entry without an author field and this fails as well. If bibtex does not require it, I think the field should be ignored if not present.

**Comment by erooke** [comment]
It depends on the entry type (article book etc), the only one I know that doesn't require an author is misc.

-------- Original Message --------

**Comment by noahares** [comment]
From what I found here: http://texdoc.net/texmf-dist/doc/bibtex/tamethebeast/ttb_en.pdf there are several entry types that do not require an author.

**Comment by erooke** [comment]
Yeah looks like:
- booklet
- manual
- misc

Don't require the author field. I had never run into the other two :sweat_smile:

**Comment by lambtho12** [comment]
Commit https://github.com/nvim-telescope/telescope-bibtex.nvim/pull/33/commits/a88a0a609ce6e4d149df8228fd2527f734a37854 should normally handle the no author case. It is only an issue when we try to abbreviate the authors firstname. For the formatting template, I already took care of the cases without a matching entry.

**Pull request merged**
