### PR TITLE
Use new actions interface 

### PR DESCRIPTION
**Pull request by noahares**
https://github.com/nvim-telescope/telescope.nvim/pull/472

### CODE REVIEW

**Comment by jghauser** [comment]
I added this change to my local files because without it, I get an error when doing `:Telescope bibtex`. However, with this change, I get an error once I select an entry in Telescope: `E5108: Error executing lua ...cker/start/telescope.nvim/lua/telescope/actions/init.lua:25: Key does not exist for 'telescope.actions': state`

It works when I remove `state` and use: `actions.get_selected_entry().value)`

**Comment by noahares** [comment]
Thanks for pointing that out. I missread something in their PR. The `state` is indeed unnessessary.

**Comment by Conni2461** [comment]
`actions.get_selected_entry` is deprecated and will be removed soon. Please use `action_state` as i mentioned before. Doesn't have to happen today just in the next week or so :) See https://github.com/nvim-telescope/telescope.nvim#mappings or example
```lua
local action_state = require('telescope.actions.state')
local entry = action_state.get_selected_entry()
```

**Comment by noahares** [comment]
Got it :)

**Pull request merged**
