### PR TITLE
Working search for specified keys

### PR DESCRIPTION
**Pull request by noahares**
Not yet happy with implementation, still needs some work.

@jghauser Feel free to test this branch. You can specify the `search_keys` as a table (see README) and then search for these as well. I am not sure how to display it properly, tho. Right now the display and preview is as before, only internally the additional keys are used. 
I would love some feedback and ideas about how to display it properly.

### CODE REVIEW

**Comment by jghauser** [comment]
This looks great! I'll test it in the next days and will get back with comments!

**Comment by jghauser** [comment]
I've started using this branch and so far I haven't had any issues. It works perfectly!

When it comes to displaying the results, i think a good example is [fzf-bibtex](https://github.com/msprev/fzf-bibtex). The results present things in the author-year-title-citation_key order, which I think is appropriate. Highlighting helps distinguishing the different types of information. Maybe this would be a good first way of doing things. Making the fields configurable would also be neat.

One problem I had with fzf-bibtex's approach is that on narrower screens (I like to have two windows next to each other), parts would get shortened because not everything fits on the screen. This often led to it being impossible to tell what the (for instance) author of a certain item is, which made selecting the right entry very hard. I'm not sure how telescope would behave in such a situation, but the problem is in any case lesser because the relevant information would also be in the preview pane. I guess this is a problem we can think about once we get to this point :D.

Is it possible to highlight matches not only in the results but also in the previews? This might be nice to have (though definitely not essential).

I'm not sure whether you intend to turn this feature on by default, but if so, I think `{ 'author', 'year', 'title'}` would be sensible defaults. I think these are the most common keys used to search academic publications.

**Comment by noahares** [comment]
Thanks for the input, will definitely have a look at fzf-bibtex. 

The highlighting in the preview is something I noticed as well. Would be really nice to have that, but I do not know if it is possible. 

With a better way to display things or the highlight in the preview, I would definitely make these options default. If that isnt possible I think there is not enough feedback to make them default.

**Comment by noahares** [comment]
Hey @jghauser, I just updated the branch. It now shows the search values while searching and I also made `author, year, title` the default search keys. I did not figure out whether highlighting in the preview is possible (might have to ask the telescope devs for this), but for now I think this more of a nice to have. This goes for coloring the different values as well (like they do it in fzf-bibtex). Let me know if you find any bugs or unintuive behavior :)

**Comment by jghauser** [comment]
Hey! Sorry for the slow response, got caught up in some things! I've had this branch running for the whole time though and didn't come across any serious issues so far. Here are some observations (not all connected to this branch specifically):

- It seems that multiline strings (in the bibtex file) get cut at the line break. This happens especially with titles (given their length).
- Searching and rendering of strings is somewhat hindered by the fact that the plugin doesn't understand latex formatting. In the case of bibtex, non-ASCII (?) characters are saved as latex. For example, `García` is saved in the bibtex file as `Garc\'{\i}a)`, which shows up in the results as `Garc\'\ia`. I'm not really sure whether anything can be done about this though, I've mostly resorted to using biblatex files instead as they use utf8.
- Even with biblatex files, searching doesn't work very well with special characters. For instance, searching for a 'i' doesn't match an 'í', which I think it should.
- I think there's an extra space before each line in the results pane. At least there seems to be more space than with other Telescope functions and the cursor in the search pane isn't lined up with the first letter in the results pane. For certain incomplete results (I think as soon as the author is missing), entries don't have this extra space and are then no longer aligned to the left with the other results
- It's not possible to scroll downwards for more results than are visible in the results pane. This might be a limitation by Telescope though, it happens the same with e.g. the frecency extension.
- Having the year (maybe in brackets) between author and title would be very handy especially when there's no colors. Currently it's all comma separated, which makes it hard to see when authors stop and the title begins.

All in all this extension is pretty brilliant and works very well! Thanks again!

**Comment by noahares** [comment]
> * It seems that multiline strings (in the bibtex file) get cut at the line break. This happens especially with titles (given their length).

This should now be fixes

> * Searching and rendering of strings is somewhat hindered by the fact that the plugin doesn't understand latex formatting. In the case of bibtex, non-ASCII (?) characters are saved as latex. For example, `García` is saved in the bibtex file as `Garc\'{\i}a)`, which shows up in the results as `Garc\'\ia`. I'm not really sure whether anything can be done about this though, I've mostly resorted to using biblatex files instead as they use utf8.
> * Even with biblatex files, searching doesn't work very well with special characters. For instance, searching for a 'i' doesn't match an 'í', which I think it should.

Both of these issues come from telescope itself, I think. Because I only hand over the search strings. Fixing this issue would require to parse all special chars manually and I have no idea how to do this (but it can be done for sure)

> * I think there's an extra space before each line in the results pane. At least there seems to be more space than with other Telescope functions and the cursor in the search pane isn't lined up with the first letter in the results pane. For certain incomplete results (I think as soon as the author is missing), entries don't have this extra space and are then no longer aligned to the left with the other results

I fixed this as well

> * It's not possible to scroll downwards for more results than are visible in the results pane. This might be a limitation by Telescope though, it happens the same with e.g. the frecency extension.

Sounds like a telescope problem

> * Having the year (maybe in brackets) between author and title would be very handy especially when there's no colors. Currently it's all comma separated, which makes it hard to see when authors stop and the title begins.

I put digit values in brackets as you suggested. I think it helps to identify them better and if one wants to check, one can always look at the preview (I dont think anyone would add "page" or as such to their list of search keys)

I know it took some time, but I think I am happy with how it turned out now. Thanks again for your feedback @jghauser

**Comment by jghauser** [comment]
Sounds great! Unfortunately I'm getting an error after updating. Do you have any idea what could be going on?

20210628_13h37m11s_grim

Also possibly of interest, in trying to troubleshoot the issue, I tried with a different bibtex file (more than twice the size, 3000+ entries) and got a different error:

20210628_13h50m39s_grim

When I delete plenty of entries from that files, I get the first error again.

About the latex escape codes. I think it's fine as it is, I'm now mostly using (somewhat unconventional) bibtex+unicode files, and everything works as expected. If you do however want to implement a conversion at some point, the table at the end of [this file](https://github.com/papis/papis/blob/231c0b011c2d8d7746e099185a7e92e0c70c6f97/papis/bibtex.py) (which converts from unicode to latex) might be a starting point. However, even this likely doesn't include all possible cases as sometimes many latex character sequences can stand for the same unicode symbol. Anyway, I think it's fine to leave it as it is.

**Comment by noahares** [comment]
For the first one I think I know what the issue is. It looks like a problem with the new parsing I implemented. I will look after it as soon as possible. 

The other one concerning memory is more tricky, as I need to basically copy the whole file for the preview (other previewers can just open the file etc on demand and display it, but the getting this to work for the bibtex entries sounds more complicated. Maybe I can save the line numbers instead of the content and then reread the file. I will see if I can figure something out

**Comment by jghauser** [comment]
Actually, no that wasn't the case. I still get the error even with the fix. I managed to find an entry that reliably triggers the error:

```bibtex
@article{allen-hermanson_superdupersizing_2013,
  author = {Allen-Hermanson, Sean},
  doi = {10.1007/s11098-012-9914-7},
  issn = {0031-8116, 1573-0883},
  journal = {Philosophical Studies},
  language = {en},
  month = {July},
  number = {3},
  pages = {791--806},
  title = {Superdupersizing the mind: extended cognition and the persistence of cognitive bloat},
  url = {http://link.springer.com/10.1007/s11098-012-9914-7},
  urldate = {2015-07-23},
  volume = {164},
  year = {2013},
}
```

Also, for me, the telescope display only shows the reference label rather than the author (year) title string.

**Comment by noahares** [comment]
Thanks, that example entry helps a lot. I thought the format was `key={value}` without whitespaces and therefore the regex does not find them (so you dont see the author, year and title). 
I will use the entry and try to debug the other issue.

**Comment by noahares** [comment]
Alright, the issue with this entry should be resolved. I also added support for all tags specified at [http://www.bibtex.org/Format/]() except that weird `"abc" # "efg"` thing.
Let me know if any issues remain besides the ones in the large bibtex file.

**Comment by jghauser** [comment]
Thanks a lot! This time it errored on another entry ;). The problem was a `.` in the citation key. I checked whether these are allowed and apparently they are. According to [this test](https://tex.stackexchange.com/questions/408530/what-characters-are-allowed-to-use-as-delimiters-for-bibtex-keys) only `{ } , ~ # % \` are disallowed (from the ASCII range).

Another thing, can you change the display for entries to: Author (Year) Title. Again, this would help with visually parsing the entries as the brackets will nicely separate authors and titles, which may (and often do) both contain commas. Another idea for enhancement would be to allow users to configure this to their liking.

**Comment by noahares** [comment]
Ok, its great to have a list. I will implement this tomorrow. 

You mean that I remove the commas between search keys? The search keys can be configured. Or do you mean wether a key is in brackets or not?

**Comment by jghauser** [comment]
Oh, mostly my bad actually! I had the search_keys configured as author, title, year and forgot that this also determines the order of what is shown in the telescope search results display list. I've changed that and now I have my desired author, year, title order. I guess my only (cosmetic, minor) issue with it now is that there's a comma after the closing bracket of the year field. But that really is minor.

Thanks a lot for all your work on this! I really like the result :)

**Comment by noahares** [comment]
Ok great! Yes, that comma is somewhat controversal :D Thanks for all the feedback. My bibtex files are very standard and therefore I don't see the issues with other (valid) formats. so your input is great to have.

**Comment by jghauser** [comment]
Loads my (not too big) bibtex file without any problems now! Thanks a lot for getting this to work so quickly! :)

**Comment by noahares** [comment]
Nice! Then I will merge this and think of a way to handle larger files.

**Pull request merged**
